import express from 'express';import pg from 'pg';import bcrypt from 'bcryptjs';import jwt from 'jsonwebtoken';import multer from 'multer';import crypto from 'crypto';import fs from 'fs';import dotenv from 'dotenv';dotenv.config();
const app=express(),db=new pg.Pool({connectionString:process.env.DATABASE_URL}),PORT=process.env.PORT||3000;fs.mkdirSync('./uploads',{recursive:true});const upload=multer({dest:'./uploads/',limits:{fileSize:8*1024*1024}});app.use(express.json());app.use(express.static('public'));
const token=u=>jwt.sign({id:u.id,role:u.role,email:u.email},process.env.JWT_SECRET,{expiresIn:'2h'});
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),process.env.JWT_SECRET);next()}catch{res.status(401).json({error:'Sessão inválida.'})}}
function admin(req,res,next){if(req.user?.role!=='admin')return res.status(403).json({error:'Acesso admin necessário.'});next()}
const ref=()=>`GC-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(2).toString('hex').toUpperCase()}`;
app.get('/api/rates',async(req,res)=>res.json((await db.query('SELECT currency,buy_rate,sell_rate,updated_at FROM rates ORDER BY currency')).rows));
app.post('/api/register',async(req,res)=>{const{x}=req.body;try{if(!x?.name||!x.email||!x.phone||!x.password)return res.status(400).json({error:'Preencha os campos obrigatórios.'});if(x.password.length<8)return res.status(400).json({error:'Senha mínima: 8 caracteres.'});const h=await bcrypt.hash(x.password,12),r=(await db.query('INSERT INTO users(name,email,phone,nif,id_document,password_hash) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,name,email,phone,nif,id_document,role',[x.name,x.email.toLowerCase(),x.phone,x.nif||null,x.id_document||null,h])).rows[0];res.status(201).json({user:r,token:token(r)})}catch(e){res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'Email já cadastrado.':'Erro ao criar conta.'})}});
app.post('/api/login',async(req,res)=>{const r=(await db.query('SELECT * FROM users WHERE email=$1',[String(req.body.email||'').toLowerCase()])).rows[0];if(!r||!(await bcrypt.compare(req.body.password||'',r.password_hash)))return res.status(401).json({error:'Email ou senha incorretos.'});delete r.password_hash;res.json({user:r,token:token(r)})});
app.get('/api/me',auth,async(req,res)=>res.json((await db.query('SELECT id,name,email,phone,nif,id_document,role FROM users WHERE id=$1',[req.user.id])).rows[0]));
app.post('/api/orders',auth,async(req,res)=>{const x=req.body,a=Number(x.foreign_amount),r=(await db.query('SELECT buy_rate FROM rates WHERE currency=$1',[x.currency])).rows[0];if(!r||!Number.isFinite(a)||a<=0)return res.status(400).json({error:'Ordem inválida.'});const q=+(a*Number(r.buy_rate)).toFixed(2),reference=ref();const o=(await db.query(`INSERT INTO orders(reference,user_id,currency,foreign_amount,kwanza_amount,rate,customer_type,fulfillment,delivery_address,withdrawal_location) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[reference,req.user.id,x.currency,a,q,r.buy_rate,x.customer_type||'national',x.fulfillment||'withdrawal',x.delivery_address||null,x.withdrawal_location||null])).rows[0];res.status(201).json(o)});
app.get('/api/orders',auth,async(req,res)=>{const sql=req.user.role==='admin'?`SELECT o.*,u.name,u.email,u.phone FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC`:`SELECT * FROM orders WHERE user_id=$1 ORDER BY created_at DESC`;res.json((await db.query(sql,req.user.role==='admin'?[]:[req.user.id])).rows)});
app.post('/api/orders/:id/proof',auth,upload.single('proof'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Comprovativo obrigatório.'});const o=(await db.query(req.user.role==='admin'?'SELECT * FROM orders WHERE id=$1':'SELECT * FROM orders WHERE id=$1 AND user_id=$2',req.user.role==='admin'?[req.params.id]:[req.params.id,req.user.id])).rows[0];if(!o)return res.status(404).json({error:'Ordem não encontrada.'});await db.query('INSERT INTO payment_proofs(order_id,filename,stored_path) VALUES($1,$2,$3)',[o.id,req.file.originalname,req.file.path]);await db.query(`UPDATE orders SET payment_status='proof_submitted',order_status='payment_review' WHERE id=$1`,[o.id]);res.json({ok:true})});
app.patch('/api/admin/orders/:id',auth,admin,async(req,res)=>{let{payment_status,order_status}=req.body,code=null,hash=null,exp=null;if(order_status==='ready'){code=String(crypto.randomInt(100000,999999));hash=await bcrypt.hash(code,12);exp=new Date(Date.now()+30*60*1000)}const o=(await db.query(`UPDATE orders SET payment_status=COALESCE($1,payment_status),order_status=COALESCE($2,order_status),withdrawal_code_hash=COALESCE($3,withdrawal_code_hash),withdrawal_code_expires=COALESCE($4,withdrawal_code_expires) WHERE id=$5 RETURNING *`,[payment_status||null,order_status||null,hash,exp,req.params.id])).rows[0];res.json({order:o,withdrawal_code:code})});
app.put('/api/admin/rates/:currency',auth,admin,async(req,res)=>{const b=Number(req.body.buy_rate),s=Number(req.body.sell_rate);if(b<=0||s<=0)return res.status(400).json({error:'Taxa inválida.'});res.json((await db.query(`INSERT INTO rates(currency,buy_rate,sell_rate) VALUES($1,$2,$3) ON CONFLICT(currency) DO UPDATE SET buy_rate=EXCLUDED.buy_rate,sell_rate=EXCLUDED.sell_rate,updated_at=NOW() RETURNING *`,[req.params.currency,b,s])).rows[0])});
app.post('/api/withdrawals/validate',async(req,res)=>{const o=(await db.query(`SELECT * FROM orders WHERE reference=$1 AND order_status='ready'`,[req.body.reference])).rows[0];if(!o)return res.status(404).json({error:'Referência não encontrada.'});if(new Date(o.withdrawal_code_expires)<new Date())return res.status(400).json({error:'Código expirado.'});if(!(await bcrypt.compare(String(req.body.code||''),o.withdrawal_code_hash)))return res.status(401).json({error:'Código inválido.'});await db.query(`UPDATE orders SET order_status='completed',withdrawal_code_hash=NULL WHERE id=$1`,[o.id]);res.json({ok:true,message:'Levantamento autorizado.'})});
app.get('/health', (req, res) => {
  res.json({ ok: true });
});
app.listen(PORT,()=>console.log('Guevara Câmbio em http://localhost:'+PORT));
